export const LOGIN_USER = "LOGIN_USER";
export const SAVE_SENDER_COMPANY = "SAVE_SENDER_COMPANY";
export const GET_SENDER_COMPANY = "GET_SENDER_COMPANY";
export const UPDATE_SENDER_COMPANY = "UPDATE_SENDER_COMPANY";
export const GET_CLIENTS = "GET_CLIENTS";
export const DELETE_CLIENT = "DELETE_CLIENT";
export const SAVE_CLIENT = "SAVE_CLIENT";
export const UPDATE_CLIENT = "UPDATE_CLIENT";
